Repository canonical/pragma, pull requests merged in 2024-12, with the labels that each got.

#48 Added basic heading styles
  packages/ds-react-core/src/ui/Typography.stories.tsx
  packages/styles/src/font-faces.css
  packages/styles/src/index.css
  packages/styles/src/typography.css
Labels: Review: Code needed, Feature 🎁

#66 Fix: declare types explicitly in packages to avoid overlapping implicit definitions
  README.md
  apps/boilerplate-react-vite/package.json
  apps/boilerplate-react-vite/tsconfig.json
  apps/ts_example/README.md
  apps/ts_example/biome.json
  apps/ts_example/package.json
  apps/ts_example/src/debounce.ts
  apps/ts_example/src/index.ts
  apps/ts_example/src/throttle.ts
  apps/ts_example/tsconfig.build.json
  apps/ts_example/tsconfig.json
  bun.lockb
  package.json
  packages/ds-react-core/vite.config.d.ts
  packages/ds-react-core/vite.config.js
  packages/utils/src/throttle.ts
Labels: Review: QA needed, Review: Code +1 (with changes), Bug 🐛

#101 chore: Fix storybook addon cleanup2
  bun.lockb
  packages/storybook-addon-baseline-grid/manager.js
  packages/storybook-addon-baseline-grid/package.json
  packages/storybook-addon-baseline-grid/preset.js
  packages/storybook-addon-baseline-grid/preview.js
  packages/storybook-addon-baseline-grid/scripts/prepublish-checks.js
  packages/storybook-addon-baseline-grid/tsconfig.build.json
  packages/storybook-addon-baseline-grid/tsup.config.ts
Labels: Review: Code +1, Review: QA +1, Maintenance 🔨

#103 chore : Storybook-addon-baseline : Added css in the addon directly, made it configurable, improved docs
  bun.lockb
  packages/ds-react-core/package.json
  packages/ds-react-core/src/index.css
  packages/storybook-addon-baseline-grid/README.md
  packages/storybook-addon-baseline-grid/src/preset.ts
  packages/storybook-addon-baseline-grid/src/withBaselineGrid.ts
  packages/styles/src/baseline-grid.css
  packages/styles/src/index.css
Labels: Review: Code +1, Review: QA +1, Maintenance 🔨
