Repository canonical/pragma, pull requests merged in 2025-04, with the labels that each got.

#189 feat: add readonly mode to the editable block component
  packages/react/ds-app-launchpad/src/ui/MarkdownEditor/MarkdownEditor.stories.tsx
  packages/react/ds-app-launchpad/src/ui/MarkdownEditor/MarkdownEditor.tests.tsx
  packages/react/ds-app-launchpad/src/ui/MarkdownEditor/MarkdownEditor.tsx
  packages/react/ds-app-launchpad/src/ui/MarkdownEditor/styles.css
  packages/react/ds-app-launchpad/src/ui/MarkdownEditor/types.ts
Labels: Review: Code +1, Review: QA +1, Feature 🎁, Review: Chromatic +1

#185 feat(Demo site): Demo Site pt. 4 - Typographic specimen styling / settings expanded
  apps/react/demo/src/assets/typographic-specimen-lines.png
  apps/react/demo/src/data/examples/TypographicSpecimen/TypographicSpecimen.tsx
  apps/react/demo/src/data/examples/TypographicSpecimen/fields.ts
  apps/react/demo/src/data/examples/TypographicSpecimen/styles.css
  apps/react/demo/src/data/fields.ts
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/Renderer.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/shadow-styles.css
  packages/react/ds-core/src/ui/Tooltip/styles.css
Labels: Review: Code needed, Review: QA needed, Feature 🎁, Review: Chromatic Needed

#192 fix: Update collapse rotate logic
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/FileHeader/styles.css
Labels: Review: Code +1, Review: QA +1, Bug 🐛, Review: Chromatic +1

#194 feat(Demo site): Add example reset button
  apps/react/demo/src/ui/Showcase/common/Example/common/Controls/Controls.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/Renderer.tsx
  apps/react/demo/src/ui/Showcase/common/Example/hooks/useProviderState.ts
  apps/react/demo/src/ui/Showcase/common/Example/types.ts
Labels: Review: Code +1, Review: QA +1, Feature 🎁

#196 fix(CodeDiffViewer): resize observer detaches on view collapse
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/styles.css
Labels: Bug 🐛

#206 feat(GitDiffViewer): improve syntax highlighting and fix file header collapse button animation
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/FileHeader/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/fixtures.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/utils/highlightDiffHunkLines.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/utils/index.ts
Labels: enhancement

#208 fix(GitDiffViewer): correct line highlighting logic in diff viewer
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/utils/highlightDiffHunkLines.ts
Labels: Bug 🐛

#209 fix: wrong import
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tsx
Labels: Bug 🐛

#210 feat(GitDiffViewer): refactor line numbers to add better support for diff lines
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/Provider.stories.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/Provider.tests.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.stories.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tests.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/AnnotatedDiffLine/AnnotatedDiffLine.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/AnnotatedDiffLine/types.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/DiffLine.tests.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/DiffLine.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/types.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/types.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/fixtures.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/types.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/utils/parseGitDiff.ts
Labels: Bug 🐛

#214 feat(React Core): Button uses `children` instead of `label` for contents
  apps/react/boilerplate-vite/src/Application.tsx
  apps/react/boilerplate-vite/src/LazyComponent.tsx
  apps/react/demo/src/data/examples/ButtonExample/ButtonExample.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Controls/Controls.tsx
  packages/react/ds-core-form/src/ui/Field/inputs/Combobox/common/ResetButton/ResetButton.tsx
  packages/react/ds-core/src/ui/Button/Button.stories.tsx
  packages/react/ds-core/src/ui/Button/Button.tests.tsx
  packages/react/ds-core/src/ui/Button/Button.tsx
  packages/react/ds-core/src/ui/Button/types.ts
  packages/react/ds-core/src/ui/Tooltip/common/TooltipArea/TooltipArea.stories.tsx
  packages/react/ds-core/src/ui/Tooltip/withTooltip.stories.tsx
Labels: Review: Code needed, Review: QA needed, Feature 🎁, Review: Chromatic Needed

#202 feat(Demo site): Apply font/baseline-relative settings
  apps/react/demo/src/data/examples/ButtonExample/fields.ts
  apps/react/demo/src/data/examples/TypographicSpecimen/TypographicSpecimen.tsx
  apps/react/demo/src/data/examples/TypographicSpecimen/fields.ts
  apps/react/demo/src/data/examples/TypographicSpecimen/styles.css
  apps/react/demo/src/data/fields.ts
  apps/react/demo/src/data/transformers.ts
  apps/react/demo/src/hooks/useExampleRHFInterface/useExampleRHFInterface.ts
  apps/react/demo/src/ui/Showcase/common/Example/common/Controls/Controls.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/Renderer.tsx
  apps/react/demo/src/ui/Showcase/common/Example/hooks/useProviderState.ts
  apps/react/demo/src/ui/Showcase/common/Example/types.ts
  packages/styles/primitives/canonical/src/typography.css
Labels: Review: Code needed, Review: QA needed, Feature 🎁, Review: Chromatic Needed
