Repository canonical/pragma, pull requests merged in 2025-09, with the labels that each got.

#315 feat(generator): Include Svelte SSR Test package
  packages/generator-ds/DEVELOPING.md
  packages/generator-ds/src/sv-component/templates/Component.ssr.test.ts.ejs
  packages/svelte/ssr-test/package.json
  packages/svelte/ssr-test/src/fixtures/Greeting.svelte
  packages/svelte/ssr-test/src/render.tests.ts
Labels: enhancement, Documentation 📝

#326 chore(deps): update @types/bun and bun-types to version 1.2.22 in lockfile
  bun.lock
Labels: Maintenance 🔨

#314 feat(React core): Implement Card component
  docs/references/STANDARDS_FOR_STYLING.md
  packages/react/ds-app-anbox/src/ui/Button/Button.stories.tsx
  packages/react/ds-app-anbox/src/ui/Button/styles.css
  packages/react/ds-app-lxd/src/ui/Button/Button.stories.tsx
  packages/react/ds-app-lxd/src/ui/Button/styles.css
  packages/react/ds-app-maas/src/ui/Button/Button.stories.tsx
  packages/react/ds-app-maas/src/ui/Button/styles.css
  packages/react/ds-app-stores/src/ui/Button/Button.stories.tsx
  packages/react/ds-app-stores/src/ui/Button/styles.css
  packages/react/ds-app-wpe/src/ui/Button/Button.stories.tsx
  packages/react/ds-app-wpe/src/ui/Button/styles.css
  packages/react/ds-app/src/ui/Button/Button.stories.tsx
  packages/react/ds-app/src/ui/Button/styles.css
  packages/react/ds-core/src/storybook/decorators.tsx
  packages/react/ds-core/src/ui/Badge/styles.css
  packages/react/ds-core/src/ui/Button/Button.stories.tsx
  packages/react/ds-core/src/ui/Button/styles.css
  packages/react/ds-core/src/ui/Card/Card.ssr.tests.tsx
  packages/react/ds-core/src/ui/Card/Card.stories.tsx
  packages/react/ds-core/src/ui/Card/Card.tests.tsx
  packages/react/ds-core/src/ui/Card/Card.tsx
  packages/react/ds-core/src/ui/Card/common/Image/Image.ssr.tests.tsx
  packages/react/ds-core/src/ui/Card/common/Image/Image.stories.tsx
  packages/react/ds-core/src/ui/Card/common/Image/Image.tests.tsx
  packages/react/ds-core/src/ui/Card/common/Image/Image.tsx
  packages/react/ds-core/src/ui/Card/common/Image/index.ts
  packages/react/ds-core/src/ui/Card/common/Image/styles.css
  packages/react/ds-core/src/ui/Card/common/Image/types.ts
  packages/react/ds-core/src/ui/Card/common/Section/Section.stories.tsx
  packages/react/ds-core/src/ui/Card/common/Section/Section.tsx
  packages/react/ds-core/src/ui/Card/common/Section/index.ts
  packages/react/ds-core/src/ui/Card/common/Section/styles.css
  packages/react/ds-core/src/ui/Card/common/Section/types.ts
  packages/react/ds-core/src/ui/Card/common/ThumbnailSection/ThumbnailSection.stories.tsx
  packages/react/ds-core/src/ui/Card/common/ThumbnailSection/ThumbnailSection.tsx
  packages/react/ds-core/src/ui/Card/common/ThumbnailSection/index.ts
  packages/react/ds-core/src/ui/Card/common/ThumbnailSection/styles.css
  packages/react/ds-core/src/ui/Card/common/ThumbnailSection/types.ts
  packages/react/ds-core/src/ui/Card/common/index.ts
  packages/react/ds-core/src/ui/Card/index.ts
  packages/react/ds-core/src/ui/Card/styles.css
  packages/react/ds-core/src/ui/Card/types.ts
  packages/react/ds-core/src/ui/Chip/styles.css
  packages/react/ds-core/src/ui/Rule/styles.css
  packages/react/ds-core/src/ui/Tooltip/styles.css
  packages/react/ds-core/src/ui/index.ts
  packages/styles/primitives/canonical/src/modifiers.css
  packages/styles/primitives/canonical/src/tokens.css
  packages/styles/primitives/canonical/src/typography.css
Labels: Review: Design needed, Review: Code +1, Review: QA +1, Feature 🎁
