Repository canonical/pragma, pull requests merged in 2025-05, with the labels that each got.

#224 refactor(FileTree): Enhance structure and styling of FileTree component
  packages/react/ds-app-launchpad/.storybook/preview.ts
  packages/react/ds-app-launchpad/src/ui/FileTree/Provider.stories.tsx
  packages/react/ds-app-launchpad/src/ui/FileTree/Provider.tests.tsx
  packages/react/ds-app-launchpad/src/ui/FileTree/Provider.tsx
  packages/react/ds-app-launchpad/src/ui/FileTree/common/Node/Provider.tsx
  packages/react/ds-app-launchpad/src/ui/FileTree/common/Node/styles.css
  packages/react/ds-app-launchpad/src/ui/FileTree/common/SearchBox/SearchBox.tsx
  packages/react/ds-app-launchpad/src/ui/FileTree/common/SearchBox/styles.css
  packages/react/ds-app-launchpad/src/ui/FileTree/common/SearchBox/types.ts
  packages/react/ds-app-launchpad/src/ui/FileTree/styles.css
  packages/react/ds-app-launchpad/src/ui/FileTree/types.ts
Labels: enhancement

#223 feat(DiffChangeMarker): add DiffChangeMarker component and include it in GitDiffViewer.FileHeader
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/DiffChangeMarker.stories.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/DiffChangeMarker.tests.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/DiffChangeMarker.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/DetailedChangeMarker/DetailedChangeMarker.tests.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/DetailedChangeMarker/DetailedChangeMarker.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/DetailedChangeMarker/index.ts
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/DetailedChangeMarker/styles.css
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/DetailedChangeMarker/types.ts
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/SimpleChangeMarker/SimpleChangeMarker.tests.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/SimpleChangeMarker/SimpleChangeMarker.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/SimpleChangeMarker/index.ts
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/SimpleChangeMarker/styles.css
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/SimpleChangeMarker/types.ts
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/common/index.ts
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/icons.tsx
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/index.ts
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/styles.css
  packages/react/ds-app-launchpad/src/ui/DiffChangeMarker/types.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/FileHeader/FileHeader.tests.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/FileHeader/FileHeader.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/FileHeader/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/styles.css
  packages/react/ds-app-launchpad/src/ui/index.ts
Labels: Feature 🎁

#227 fix(CodeDiffViewer): improve component rendering
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/index.ts
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/utils/updateTableWidth.ts
  packages/react/ds-app-launchpad/src/ui/MarkdownEditor/hooks/useEditor.ts
Labels: Bug 🐛

#205 feat(Demo site): Navbar enhancements
  apps/react/demo/index.html
  apps/react/demo/package.json
  apps/react/demo/src/Application.tsx
  apps/react/demo/src/data/examples/TypographicSpecimen/TypographicSpecimen.tsx
  apps/react/demo/src/data/examples/TypographicSpecimen/styles.css
  apps/react/demo/src/hooks/useExampleRHFInterface/useExampleRHFInterface.ts
  apps/react/demo/src/index.css
  apps/react/demo/src/ui/Drawer/styles.css
  apps/react/demo/src/ui/Showcase/Showcase.stories.tsx
  apps/react/demo/src/ui/Showcase/Showcase.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Controls/Controls.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Controls/styles.css
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/Renderer.tsx
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/shadow-styles.css
  apps/react/demo/src/ui/Showcase/common/Example/common/Renderer/styles.css
  apps/react/demo/src/ui/Showcase/common/Example/hooks/useProviderState.ts
  apps/react/demo/src/ui/Showcase/common/Example/types.ts
  apps/react/demo/src/ui/Showcase/styles.css
  apps/react/demo/src/ui/index.ts
  bun.lock
  packages/react/ds-core/src/ui/tooltip_exploration.md
Labels: Review: Code needed, Review: QA needed, Feature 🎁, Review: Chromatic Needed
