Repository canonical/pragma, pull requests merged in 2025-06, with the labels that each got.

#269 refactor(GitDiffViewer): fix comment icon alignment and add line hover effect
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/CodeDiffViewer.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/DiffLine.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/DiffLine/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/common/icons.tsx
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/common/CodeDiffViewer/styles.css
  packages/react/ds-app-launchpad/src/ui/GitDiffViewer/styles.css
Labels: Maintenance 🔨

#267 feat(generator): Generate SSR output test file
  packages/generator-ds/src/component/README.md
  packages/generator-ds/src/component/index.ts
  packages/generator-ds/src/component/templates/Component.ssr.tests.tsx.ejs
  packages/generator-ds/src/sv-component/README.md
  packages/generator-ds/src/sv-component/index.ts
  packages/generator-ds/src/sv-component/templates/Component.ssr.test.ts.ejs
  packages/generator-ds/src/sv-component/templates/Component.svelte.test.ts.ejs
  packages/react/ds-core/src/ui/Button/Button.ssr.tests.tsx
  packages/react/ds-core/vitest.config.ts
Labels: Feature 🎁

#280 chore(Chromatic): Chromatic runs on main branch to update baseline
  .github/workflows/chromatic._template.yml
  .github/workflows/chromatic.demo.yml
  .github/workflows/chromatic.ds-react-app-anbox.yml
  .github/workflows/chromatic.ds-react-app-launchpad.yml
  .github/workflows/chromatic.ds-react-app-lxd.yml
  .github/workflows/chromatic.ds-react-app-maas.yml
  .github/workflows/chromatic.ds-react-app-stores.yml
  .github/workflows/chromatic.ds-react-app-wpe.yml
  .github/workflows/chromatic.ds-react-core-form.yml
  .github/workflows/chromatic.ds-react-core.yml
  .github/workflows/chromatic.react-boilerplate-vite.yml
Labels: Review: Code needed, Review: QA needed, Bug 🐛, Maintenance 🔨
